name: CI/CD Pipeline

on:
  push:
    branches: [ Docker ]
  pull_request:
    branches: [ Docker ]

jobs:  
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create domain
      run: |
        curl -d "srv=${{ secrets.SERVER_ID }}&key=${{ secrets.HOSTING_API_KEY }}&port=80&domain=p2paw.bieda.it" https://api.mikr.us/domain

    - name: Build and run docker-compose
      run: |
        docker-compose up -d

    - name: Run tests
      run: |
        echo "Running tests"
        # Insert your commands to run tests here

    - name: Deploy to VPS
      run: |
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/authorized_keys
        ssh-keygen -lf ~/.ssh/id_ed25519
        scp -vvv -o StrictHostKeyChecking=no -P 10522 -r ${GITHUB_WORKSPACE}/ root@srv22.mikr.us:/root
        ssh -vvv -o StrictHostKeyChecking=no -p 10522 [your-username]@[your-vps-ip] "cd /root/P2-PAW && docker-compose up -d"

    - name: Cleanup
      if: always()
      run: docker-compose down
