name: test CI/CD Pipeline

on:
  push:
    branches: [ Docker ]
  pull_request:
    branches: [ Docker ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run docker-compose
      run: |
        docker-compose up -d
    - name: Run tests
      run: |
        echo "Running tests"
        # Insert your commands to run tests here
    - name: Cleanup
      if: always()
      run: docker-compose down
